// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BancoQuestoes","status":true,"description":"Banco de questões matemáticas por inimigo","parameters":{}},
{"name":"DesafioMatematico","status":true,"description":"Sistema de desafios matemáticos - Etapa 2","parameters":{}}
];
